In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [5]:
dd=pd.read_csv("C:/Users/Hema/Downloads/retail_sales_dataset.csv")

In [6]:
dd.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [7]:
dd.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [8]:
dd.size

9000

In [9]:
dd.shape

(1000, 9)

In [10]:
dd.columns

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount'],
      dtype='str')

In [11]:
dd.isnull()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False

In [12]:
dd.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [13]:
dd.dropna(inplace=True)
numeric_dd=dd.select_dtypes(include="number")
result=pd.DataFrame({
    "Mean":numeric_dd.mean(),
    "Median":numeric_dd.median(),
    "Mode":numeric_dd.mode().iloc[0]
})
print(result.round(3))

                   Mean  Median  Mode
Transaction ID  500.500   500.5   1.0
Age              41.392    42.0  43.0
Quantity          2.514     3.0   4.0
Price per Unit  179.890    50.0  50.0
Total Amount    456.000   135.0  50.0

In [14]:
dd.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [15]:
dd.duplicated().sum()

np.int64(0)

In [16]:
pd.to_datetime(dd["Date"])

0     2023-11-24
1     2023-02-27
2     2023-01-13
3     2023-05-21
4     2023-05-06
         ...
995   2023-05-16
996   2023-11-17
997   2023-10-29
998   2023-12-05
999   2023-04-12
Name: Date, Length: 1000, dtype: datetime64[us]

In [17]:
dd.loc[0:3,["Product Category","Quantity"]]

  Product Category  Quantity
0           Beauty         3
1         Clothing         2
2      Electronics         1
3         Clothing         1

In [18]:
dd.iloc[0:5]

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [20]:
dd["Calculated_Amount"] = dd["Quantity"] * dd["Price per Unit"]
print(dd.head())

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount  Calculated_Amount
0         3              50           150                150
1         2             500          1000               1000
2         1              30            30                 30
3         1             500           500                500
4         2              50           100                100

In [21]:
print(dd.groupby("Gender")["Total Amount"].sum())

Gender
Female    232840
Male      223160
Name: Total Amount, dtype: int64

In [22]:
le = LabelEncoder()
dd["Gender1"] = le.fit_transform(dd["Gender"])

print(dd.head())

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount  Calculated_Amount  Gender1
0         3              50           150                150        1
1         2             500          1000               1000        0
2         1              30            30                 30        1
3         1             500           500                500        1
4         2              50           100                100        1

In [26]:
oe = OrdinalEncoder(categories=[["Beauty", "Electronics", "Clothing"]])
dd["Category1"] = oe.fit_transform(dd[["Product Category"]])
print(dd.head())

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty

   Quantity  Price per Unit  Total Amount  Calculated_Amount  Gender1  \
0         3              50           150                150        1
1         2             500          1000               1000        0
2         1              30            30                 30        1
3         1             500           500                500        1
4         2              50           100                100        1

   Category1
0        0.0
1        2.0
2        1.0
3        2.0
4        0.0

In [27]:
dd = pd.get_dummies(dd, columns=["Product Category"], dtype=int)
print(dd.head())

   Transaction ID        Date Customer ID  Gender  Age  Quantity  \
0               1  2023-11-24     CUST001    Male   34         3
1               2  2023-02-27     CUST002  Female   26         2
2               3  2023-01-13     CUST003    Male   50         1
3               4  2023-05-21     CUST004    Male   37         1
4               5  2023-05-06     CUST005    Male   30         2

   Price per Unit  Total Amount  Calculated_Amount  Gender1  Category1  \
0              50           150                150        1        0.0
1             500          1000               1000        0        2.0
2              30            30                 30        1        1.0
3             500           500                500        1        2.0
4              50           100                100        1        0.0

   Product Category_Beauty  Product Category_Clothing  \
0                        1                          0
1                        0                          1
2                        0                          0
3                        0                          1
4                        1                          0

   Product Category_Electronics
0                             0
1                             0
2                             1
3                             0
4                             0