In [30]:
import pandas as pd

In [31]:
import numpy as np

In [32]:
hemi=pd.read_csv("C:/Users/Hema/Downloads/student_exam_performance.csv")

In [33]:
print(hemi)

       student_id  age  gender education_level school_type family_income  \
0      STU_000001   20  Female     High School      Public        Middle
1      STU_000002   17    Male     High School      Public        Middle
2      STU_000003   18   Other   Undergraduate      Public        Middle
3      STU_000004   20    Male     High School      Public        Middle
4      STU_000005   16  Female     High School     Private          High
...           ...  ...     ...             ...         ...           ...
99995  STU_099996   17    Male   Undergraduate      Public  Upper-Middle
99996  STU_099997   14  Female     High School      Public  Upper-Middle
99997  STU_099998   16  Female     High School      Public  Upper-Middle
99998  STU_099999   15  Female     High School     Private          High
99999  STU_100000   18  Female   Undergraduate     Charter  Lower-Middle

      parent_education urban_rural  previous_exam_score  previous_gpa  ...  \
0                  NaN       Rural                78.36          2.95  ...
1                  NaN    Suburban                73.40          2.89  ...
2               Master       Urban                82.76          3.35  ...
3          High School    Suburban                60.61          2.57  ...
4             Bachelor    Suburban                74.79          2.84  ...
...                ...         ...                  ...           ...  ...
99995              NaN    Suburban                78.73           NaN  ...
99996         Bachelor    Suburban                75.70          2.98  ...
99997      High School    Suburban                84.69          3.27  ...
99998           Master       Rural                74.70          3.06  ...
99999              NaN       Urban                76.73          2.97  ...

       exam_difficulty  exam_preparation_days questions_attempted  \
0               Medium                     27                  95
1                 Easy                      4                 100
2                 Easy                     28                  96
3               Medium                     16                  97
4               Medium                     28                  98
...                ...                    ...                 ...
99995           Medium                      5                  95
99996             Easy                     24                  94
99997           Medium                     24                  85
99998           Medium                     28                  93
99999           Medium                      1                  92

       questions_correct  time_management_score  exam_anxiety_level  \
0                     86                    NaN                9.39
1                     86                  87.17                6.31
2                     74                  63.77                9.87
3                     77                  59.51                9.68
4                     52                  84.64               10.00
...                  ...                    ...                 ...
99995                 62                  76.13                8.36
99996                 91                  84.29                8.68
99997                 65                  62.32                9.97
99998                 81                 100.00               10.00
99999                 52                    NaN               10.00

       exam_score performance_grade pass_status performance_level
0           90.40                 A        Pass              High
1           86.21                 A        Pass              High
2           76.11                 B        Pass            Medium
3           79.74                 B        Pass            Medium
4           50.66                 D        Pass               Low
...           ...               ...         ...               ...
99995       66.46                 C        Pass            Medium
99996       96.54                 A        Pass              High
99997       74.66                 C        Pass            Medium
99998       85.85                 A        Pass              High
99999       54.40                 D        Pass               Low

[100000 rows x 44 columns]

In [34]:
hemi["education_level"]

0          High School
1          High School
2        Undergraduate
3          High School
4          High School
             ...
99995    Undergraduate
99996      High School
99997      High School
99998      High School
99999    Undergraduate
Name: education_level, Length: 100000, dtype: str

In [35]:
hemi.loc[1:20,["student_id","education_level"]]

    student_id education_level
1   STU_000002     High School
2   STU_000003   Undergraduate
3   STU_000004     High School
4   STU_000005     High School
5   STU_000006     High School
6   STU_000007     High School
7   STU_000008   Undergraduate
8   STU_000009   Undergraduate
9   STU_000010   Undergraduate
10  STU_000011     High School
11  STU_000012     High School
12  STU_000013   Undergraduate
13  STU_000014     High School
14  STU_000015     High School
15  STU_000016     High School
16  STU_000017     High School
17  STU_000018   Undergraduate
18  STU_000019     High School
19  STU_000020     High School
20  STU_000021     High School

In [38]:
hemi.iloc[0:10,0:5]

   student_id  age  gender education_level school_type
0  STU_000001   20  Female     High School      Public
1  STU_000002   17    Male     High School      Public
2  STU_000003   18   Other   Undergraduate      Public
3  STU_000004   20    Male     High School      Public
4  STU_000005   16  Female     High School     Private
5  STU_000006   18    Male     High School      Public
6  STU_000007   18    Male     High School     Charter
7  STU_000008   20  Female   Undergraduate     Private
8  STU_000009   15    Male   Undergraduate      Public
9  STU_000010   16  Female   Undergraduate      Public

In [46]:
hemi.loc[hemi["age"]>15,["education_level","gender"]]

      education_level  gender
0         High School  Female
1         High School    Male
2       Undergraduate   Other
3         High School    Male
4         High School  Female
...               ...     ...
99992     High School  Female
99993     High School    Male
99995   Undergraduate    Male
99997     High School  Female
99999   Undergraduate  Female

[71447 rows x 2 columns]

In [47]:
hemi.loc[hemi["age"]>=15,["education_level","gender"]]

      education_level  gender
0         High School  Female
1         High School    Male
2       Undergraduate   Other
3         High School    Male
4         High School  Female
...               ...     ...
99994     High School    Male
99995   Undergraduate    Male
99997     High School  Female
99998     High School  Female
99999   Undergraduate  Female

[85771 rows x 2 columns]

In [48]:
hemi.loc[hemi["age"]<15,["education_level","gender"]]

      education_level  gender
25      Undergraduate  Female
31      Undergraduate    Male
32        High School    Male
48      Undergraduate    Male
54      Undergraduate  Female
...               ...     ...
99971   Undergraduate    Male
99983     High School    Male
99984     High School  Female
99988     High School    Male
99996     High School  Female

[14229 rows x 2 columns]

In [49]:
hemi.loc[hemi["age"]<=15,["education_level","gender"]]

      education_level  gender
8       Undergraduate    Male
18        High School  Female
22        High School    Male
25      Undergraduate  Female
27        High School    Male
...               ...     ...
99988     High School    Male
99990     High School  Female
99994     High School    Male
99996     High School  Female
99998     High School  Female

[28553 rows x 2 columns]

In [50]:
hemi[(hemi["age"]>14)|(hemi["previous_exam_score"]>80)]

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,STU_099995,15,Male,High School,Public,Low,Associate,Urban,54.37,2.13,...,Easy,5,97,39,79.83,10.00,40.70,F,Fail,Low
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [51]:
hemi[(hemi["age"]>14)&(hemi["previous_exam_score"]>80)]

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
7,STU_000008,20,Female,Undergraduate,Private,Lower-Middle,Bachelor,Suburban,90.79,3.63,...,Easy,7,94,91,88.08,10.00,97.61,A,Pass,High
11,STU_000012,16,Male,High School,Public,Upper-Middle,Associate,Urban,94.04,3.85,...,Medium,3,94,74,89.89,10.00,77.19,B,Pass,Medium
19,STU_000020,17,Female,High School,Private,Lower-Middle,Associate,Urban,87.54,3.52,...,Medium,28,93,64,81.07,10.00,70.56,C,Pass,Medium
24,STU_000025,18,Male,Undergraduate,Private,Upper-Middle,Associate,Suburban,86.91,3.58,...,Hard,24,97,68,100.00,8.78,72.34,C,Pass,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99974,STU_099975,15,Male,High School,Public,Upper-Middle,Bachelor,Urban,81.55,3.11,...,Easy,7,97,81,88.92,10.00,84.07,B,Pass,High
99977,STU_099978,19,Female,High School,Private,High,High School,Suburban,91.10,3.46,...,Hard,30,98,67,97.06,10.00,67.38,C,Pass,Medium
99989,STU_099990,16,Male,High School,Public,Upper-Middle,High School,Urban,81.37,3.22,...,Easy,19,88,83,76.66,7.06,91.43,A,Pass,High
99993,STU_099994,17,Male,High School,Public,Upper-Middle,High School,Urban,86.48,3.64,...,Easy,22,91,73,74.99,6.92,80.46,B,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium

In [54]:
hemi[~(hemi["age"]>18)]

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
5,STU_000006,18,Male,High School,Public,High,High School,Rural,67.68,NaN,...,Hard,27,96,65,55.27,6.12,67.90,C,Pass,Medium
6,STU_000007,18,Male,High School,Charter,Middle,NaN,Urban,78.84,3.00,...,Hard,12,98,54,86.15,9.46,53.86,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [55]:
hemi.sort_values("age")

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
58,STU_000059,14,Male,Undergraduate,Private,Lower-Middle,High School,Rural,67.59,2.96,...,Medium,3,95,66,100.00,9.23,72.53,C,Pass,Medium
63,STU_000064,14,Female,Undergraduate,Public,Lower-Middle,Associate,Urban,58.77,2.08,...,Hard,23,99,78,74.58,8.86,79.10,B,Pass,Medium
71314,STU_071315,14,Female,Undergraduate,Public,Lower-Middle,Master,Urban,57.96,2.41,...,Easy,21,99,66,61.86,9.14,67.94,C,Pass,Medium
71323,STU_071324,14,Male,Undergraduate,Public,Middle,High School,Suburban,81.30,3.28,...,Medium,27,88,54,79.81,10.00,64.20,D,Pass,Medium
71324,STU_071325,14,Male,High School,Private,Middle,NaN,Rural,79.58,3.17,...,Medium,17,92,79,74.55,10.00,89.13,A,Pass,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71341,STU_071342,20,Male,Undergraduate,Private,Middle,Associate,Urban,66.00,2.70,...,Hard,16,100,75,71.62,6.58,75.55,B,Pass,Medium
71340,STU_071341,20,Male,High School,Private,High,High School,Rural,63.60,2.52,...,Medium,12,93,54,80.89,10.00,56.90,D,Pass,Low
46,STU_000047,20,Female,High School,Public,Middle,Master,Rural,81.12,3.34,...,Hard,3,91,64,73.60,9.50,70.64,C,Pass,Medium
71321,STU_071322,20,Female,Undergraduate,Public,Low,Bachelor,Urban,75.34,3.17,...,Easy,28,88,78,65.48,8.15,86.81,A,Pass,High
71338,STU_071339,20,Female,Undergraduate,Private,Lower-Middle,High School,Suburban,59.23,2.44,...,Hard,16,90,42,75.44,9.97,47.87,F,Fail,Low

In [56]:
hemi.sort_values(by=["previous_exam_score","student_id"],ascending=[True,False])

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
98737,STU_098738,16,Female,Undergraduate,Public,Lower-Middle,Bachelor,Suburban,30.0,1.01,...,Easy,18,90,35,97.82,9.10,40.43,F,Fail,Low
95046,STU_095047,18,Female,Undergraduate,Charter,Low,Master,Rural,30.0,1.14,...,Medium,12,89,50,89.99,4.88,54.18,D,Pass,Low
80275,STU_080276,14,Male,High School,Private,Upper-Middle,Associate,Urban,30.0,1.60,...,Medium,18,86,42,83.75,7.53,47.40,F,Fail,Low
79987,STU_079988,14,Female,Undergraduate,Public,Upper-Middle,Bachelor,Urban,30.0,1.34,...,Easy,24,89,69,59.79,10.00,79.00,B,Pass,Medium
78472,STU_078473,14,Male,High School,Private,Low,Bachelor,Urban,30.0,1.71,...,Hard,17,90,31,95.91,10.00,31.95,F,Fail,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,STU_000819,18,Male,High School,Public,High,Master,Urban,100.0,3.92,...,Easy,22,89,73,73.27,8.61,81.16,B,Pass,High
381,STU_000382,19,Female,Undergraduate,Private,Lower-Middle,Bachelor,Suburban,100.0,4.00,...,Hard,16,96,80,81.03,7.43,85.60,A,Pass,High
158,STU_000159,19,Female,High School,Public,Lower-Middle,NaN,Suburban,100.0,NaN,...,Hard,7,87,48,NaN,10.00,57.63,D,Pass,Low
144,STU_000145,14,Female,Undergraduate,Public,Lower-Middle,Master,Suburban,100.0,3.94,...,Medium,17,92,69,74.48,10.00,73.98,C,Pass,Medium
25,STU_000026,14,Female,Undergraduate,Public,Upper-Middle,High School,Suburban,100.0,4.00,...,Hard,25,91,59,64.33,10.00,66.40,C,Pass,Medium

In [58]:
hemi["total"]=hemi["questions_correct"]+hemi["questions_attempted"]
hemi.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level,total
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,27,95,86,NaN,9.39,90.40,A,Pass,High,181
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,4,100,86,87.17,6.31,86.21,A,Pass,High,186
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,28,96,74,63.77,9.87,76.11,B,Pass,Medium,170
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,16,97,77,59.51,9.68,79.74,B,Pass,Medium,174
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,28,98,52,84.64,10.00,50.66,D,Pass,Low,150

In [59]:
hemi["total"]=hemi["questions_correct"]-hemi["questions_attempted"]
hemi.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level,total
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,27,95,86,NaN,9.39,90.40,A,Pass,High,-9
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,4,100,86,87.17,6.31,86.21,A,Pass,High,-14
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,28,96,74,63.77,9.87,76.11,B,Pass,Medium,-22
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,16,97,77,59.51,9.68,79.74,B,Pass,Medium,-20
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,28,98,52,84.64,10.00,50.66,D,Pass,Low,-46

In [66]:
hemi["total"]=hemi["questions_correct"]*hemi["questions_attempted"]
hemi.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level,total
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,27,95,86,NaN,9.39,90.40,A,Pass,High,8170
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,4,100,86,87.17,6.31,86.21,A,Pass,High,8600
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,28,96,74,63.77,9.87,76.11,B,Pass,Medium,7104
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,16,97,77,59.51,9.68,79.74,B,Pass,Medium,7469
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,28,98,52,84.64,10.00,50.66,D,Pass,Low,5096

In [61]:
hemi.groupby("previous_exam_score")["previous_gpa"].sum()

previous_exam_score
30.00       22.64
30.05        1.24
30.11        1.10
30.23        1.25
30.39        1.29
           ...
99.96        8.00
99.97        3.98
99.98        7.97
99.99        4.00
100.00    1480.10
Name: previous_gpa, Length: 6153, dtype: float64

In [62]:
hemi.groupby("previous_exam_score")["previous_gpa"].min()

previous_exam_score
30.00     1.00
30.05     1.24
30.11     1.10
30.23     1.25
30.39     1.29
          ...
99.96     4.00
99.97     3.98
99.98     3.97
99.99     4.00
100.00    3.52
Name: previous_gpa, Length: 6153, dtype: float64

In [63]:
hemi.groupby("previous_exam_score")["previous_gpa"].max()

previous_exam_score
30.00     1.71
30.05     1.24
30.11     1.10
30.23     1.25
30.39     1.29
          ...
99.96     4.00
99.97     3.98
99.98     4.00
99.99     4.00
100.00    4.00
Name: previous_gpa, Length: 6153, dtype: float64

In [64]:
hemi.groupby("previous_exam_score")["previous_gpa"].count()

previous_exam_score
30.00      18
30.05       1
30.11       1
30.23       1
30.39       1
         ...
99.96       2
99.97       1
99.98       2
99.99       1
100.00    376
Name: previous_gpa, Length: 6153, dtype: int64

In [65]:
hemi.groupby("previous_exam_score")["previous_gpa"].mean()

previous_exam_score
30.00     1.257778
30.05     1.240000
30.11     1.100000
30.23     1.250000
30.39     1.290000
            ...
99.96     4.000000
99.97     3.980000
99.98     3.985000
99.99     4.000000
100.00    3.936436
Name: previous_gpa, Length: 6153, dtype: float64